/** Declaration file generated by dts-gen */

export = ajv_keywords

declare function ajv_keywords(ajv: any, keyword: any): any

declare namespace ajv_keywords {
	// eslint-disable-next-line @typescript-eslint/ban-types
	const prototype: {}

	function get(keyword: any): any

	namespace get {
		// eslint-disable-next-line @typescript-eslint/ban-types
		const prototype: {}
	}
}

